### ISSUE TITLE
NAT not working

### ISSUE THREAD

**Issue by bonnebulle** [devgiants/livebox#4]
Thanks, 
very good stuff here, why I dont search for it one year ago...

But when I try to add a NAT port (or just get NAT:infos) I have this error message
  There are no commands defined in the "nat" namespace.

wan:infos of wifi:switch working great !

Merci :)

**Comment by devgiants** [comment]
Hi there,

Thanks for your message. To be sure, could you confirm that your using `nat` namespace, lowerspace? You could experience some casing issue only.

Cheers,

**Comment by bonnebulle** [comment]
Yep, i try, not working ("nat"/"NAT")
. thanks, you give me the clue : https://github.com/rene-d/sysbus
. can import/export NAT rules...
